# Generated by Django 3.1.6 on 2021-02-11 16:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255, verbose_name='Your FULL name')),
                ('Email', models.EmailField(max_length=255, verbose_name='Your SCHOOL email')),
                ('Title', models.CharField(max_length=255, unique=True, verbose_name='Title of the book')),
                ('Author', models.CharField(max_length=255, verbose_name='Author of the book')),
                ('Description', models.TextField(blank=True, null=True, verbose_name='Summary of the book (Optional)')),
                ('PageCount', models.PositiveIntegerField(blank=True, null=True, verbose_name='Number of pages in the book (Optional)')),
                ('GradeLevel', models.CharField(blank=True, choices=[('K-2', 'K-2'), ('3-5', '3-5'), ('6-8', '6-8'), ('9-12', '9-12'), ('Young Adult', 'Young Adult')], default='6-8', max_length=20, null=True, verbose_name='Grade Level of this book (Default is 6-8)')),
                ('Rating', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Rating out of 10')),
            ],
        ),
    ]
