# Generated by Django 3.1.2 on 2020-11-12 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookresponse',
            old_name='author',
            new_name='Author',
        ),
        migrations.RenameField(
            model_name='bookresponse',
            old_name='desc',
            new_name='Description',
        ),
        migrations.RenameField(
            model_name='bookresponse',
            old_name='YourEmail',
            new_name='Email',
        ),
        migrations.RenameField(
            model_name='bookresponse',
            old_name='YourName',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='bookresponse',
            old_name='rating',
            new_name='Rating',
        ),
        migrations.RenameField(
            model_name='bookresponse',
            old_name='title',
            new_name='Title',
        ),
    ]
