# Generated by Django 3.1.2 on 2021-01-26 21:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookresponse',
            name='ContainsBadWords',
            field=models.BooleanField(blank=True, null=True, verbose_name='Does this book contain bad words? (Bad for an 8 year old)'),
        ),
        migrations.AddField(
            model_name='bookresponse',
            name='PageCount',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Number of pages in the book (Optional)'),
        ),
        migrations.AddField(
            model_name='bookresponse',
            name='Summary',
            field=models.TextField(blank=True, null=True, verbose_name='Summary of the book (Optional)'),
        ),
        migrations.AlterField(
            model_name='bookresponse',
            name='Author',
            field=models.CharField(max_length=255, verbose_name='Author of the book'),
        ),
        migrations.AlterField(
            model_name='bookresponse',
            name='Description',
            field=models.TextField(blank=True, null=True, verbose_name='Description of the book (Optional)'),
        ),
        migrations.AlterField(
            model_name='bookresponse',
            name='Email',
            field=models.EmailField(max_length=255, verbose_name='Your SCHOOL email'),
        ),
        migrations.AlterField(
            model_name='bookresponse',
            name='Name',
            field=models.CharField(max_length=255, verbose_name='Your FULL name'),
        ),
        migrations.AlterField(
            model_name='bookresponse',
            name='Rating',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Rating out of 10'),
        ),
        migrations.AlterField(
            model_name='bookresponse',
            name='Title',
            field=models.CharField(max_length=255, unique=True, verbose_name='Title of the book'),
        ),
    ]
