# Generated by Django 3.1.6 on 2021-02-11 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmodel',
            name='ContainsBadWords',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
