# Generated by Django 3.1.2 on 2021-01-26 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20210126_1547'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookresponse',
            name='Description',
        ),
    ]
