# Generated by Django 3.1.6 on 2021-02-11 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_bookmodel_containsbadwords'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookmodel',
            name='ContainsBadWords',
        ),
    ]
