# Generated by Django 3.1.6 on 2021-02-18 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_bookmodel_gradelevel'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmodel',
            name='ImportantBook',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bookmodel',
            name='GradeLevel',
            field=models.CharField(choices=[('K-2', 'K-2'), ('3-5', '3-5'), ('6-8', '6-8'), ('9-12', '9-12'), ('Young Adult', 'Young Adult')], default='6-8', max_length=20, verbose_name='Grade Level of this book (Default is 6-8)'),
        ),
    ]
