# Generated by Django 3.1.2 on 2021-01-27 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_auto_20210127_0831'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BookResponse',
            new_name='BookModel',
        ),
    ]
