# Generated by Django 3.1.6 on 2021-02-13 20:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_remove_bookmodel_gradelevel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmodel',
            name='Email',
            field=models.EmailField(max_length=255, verbose_name='Your PERSONAL email'),
        ),
        migrations.AlterField(
            model_name='bookmodel',
            name='Rating',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Rating out of 10'),
        ),
    ]
