# Generated by Django 3.1.6 on 2021-02-09 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_auto_20210207_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmodel',
            name='ContainsBadWords',
            field=models.BooleanField(verbose_name='Is this book inappropriate for someone around 8 years old?'),
        ),
    ]
